# Generated by Django 5.2.5 on 2025-09-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('full_name_kana', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('job', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
