# Generated by Django 5.2.5 on 2025-09-18 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_category_store_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='category',
        ),
    ]
